// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rznTdlkTApj_ryKrj_M2cxMG_NVpF9Q',
    appId: '1:127285274346:web:4b1ce02fb919416f0b1993',
    messagingSenderId: '127285274346',
    projectId: 'ayopemilu-id',
    authDomain: 'ayopemilu-id.firebaseapp.com',
    storageBucket: 'ayopemilu-id.appspot.com',
    measurementId: 'G-JQB83ZEZ3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxV_IGCG0FzewEseet7jjtKeS8UDcCU0',
    appId: '1:127285274346:android:5a64a7792a2a61a30b1993',
    messagingSenderId: '127285274346',
    projectId: 'ayopemilu-id',
    storageBucket: 'ayopemilu-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR454X31AUwp-Bv9BXfuEYzLngHn7jqNo',
    appId: '1:127285274346:ios:4de47e258f3d693d0b1993',
    messagingSenderId: '127285274346',
    projectId: 'ayopemilu-id',
    storageBucket: 'ayopemilu-id.appspot.com',
    iosClientId: '127285274346-dcuq0j76kh689me10bef8g06tduhkuli.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayopemiluMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR454X31AUwp-Bv9BXfuEYzLngHn7jqNo',
    appId: '1:127285274346:ios:07fd0e533b6c9b820b1993',
    messagingSenderId: '127285274346',
    projectId: 'ayopemilu-id',
    storageBucket: 'ayopemilu-id.appspot.com',
    iosClientId: '127285274346-j43fmbn7n74m2r4ueu2iatl372eh4vdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayopemiluMobile.RunnerTests',
  );
}
